### ISSUE TITLE
It would be convenient to solve this problem that through you see the Name and therefore you cannot see the player well

### ISSUE THREAD

**Issue by Nukecraft5419** [Hoetty/better-name-visibility#5]
![2023-06-17_21 48 04](https://github.com/Hoetty/better-name-visibility/assets/72621737/4b5736d2-9a5c-4d1e-a0f3-912eeac2fb82)

**Comment by Hoetty** [comment]
Works as intended

**Comment by Nukecraft5419** [comment]
True, I checked in vanilla as well, it's just that this mod encourages more visibility of names so it's normal, I apologise however the mod is currently available in the modpack created by my team LifeMC Studios which is coming out soon
